### PR TITLE
Require Rack 3.0+, Ruby 3.1+, bump version to 1.0.0

### PR DESCRIPTION
**Pull request by dentarg**
The rest as reached end of life: https://www.ruby-lang.org/en/downloads/

### CODE REVIEW

**Comment by dentarg** [comment]
Oh, we should absolutely be compatible with the latest rack-test (and rack) before we do this.

**Comment by dentarg** [comment]
@olleolleolle Wanna take a look?

**Comment by olleolleolle** [comment]
@dentarg Looks good from here!

**Comment by olleolleolle** [comment]
perhaps we wish the CHANGELOG to reflect these updates?

**Comment by olleolleolle** [comment]
Nice with the names in the CI matrix, this all looks good to go!

**Comment by dentarg** [comment]
Released now! https://rubygems.org/gems/spinels-rack-ssl-enforcer

**Pull request merged**
